WebApp/Pages/Play/Index.cshtml.cs
using CardSystem;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlayerSystem;
using UnoGame;

namespace WebApp.Pages.Play;

public class Index : PageModel
{
    private readonly GameContext _context;
    public ISaveLoadGame SaveLoadGame;
    [BindProperty(SupportsGet = true)] public Guid GameId { get; set; }
    [BindProperty(SupportsGet = true)] public Guid PlayerId { get; set; }
    public GameState GameState { get; set; } = default!;
    [BindProperty(SupportsGet = true)] public string? Saver { get; set; }
    public List<Card> PlayerCardsInGame = default!;

    public Index(GameContext context)
    {
        _context = context;
        SaveLoadGame = new SaveToDataBase(_context);
    }
    
    public void OnGet()
    {
        SaveLoadGame = Saver!.Equals("Database") ? new SaveToDataBase(_context) : new SaveToJsonFile();
        InitializeGameState();
        var currentPlayer = GameState.GameConfigurations.Players[GameState.PlayerIndex];
        ApplyActionCardForPlayer(currentPlayer, GameState.CardOnTheTable);
        if (currentPlayer.MustSkip)
        {
            GameState.PlayerIndex = (GameState.PlayerIndex + 1) % GameState.GameConfigurations.Players.Count;
            GameState.SaveLoadGame.SaveGame(GameState.Id, GameState);
            return;
        }
        if (currentPlayer.PlayerType == PlayerType.Ai)
        {
            if (currentPlayer.PlayerHand.Count == 1 && GameState.IsValidMove ||  currentPlayer.PlayerHand.Count == 0 )
            {
                GameState.GameIsOver = true;
            }
            GameState.HandleAiPlayerLogic(currentPlayer);
            PlayRound(currentPlayer);
            currentPlayer.MustSkip = false;
            GameState.PlayerIndex = (GameState.PlayerIndex + 1) % GameState.GameConfigurations.Players.Count;
        }
        GameState.SaveLoadGame.SaveGame(GameState.Id, GameState);
    }

    public void InitializeGameState()
    {
        SaveLoadGame = Saver!.Equals("Database") ? new SaveToDataBase(_context) : new SaveToJsonFile();
        GameState = SaveLoadGame.LoadGame(GameId);
        GameState.SaveLoadGame = SaveLoadGame;
        PlayerCardsInGame = GameState.GameConfigurations.Players.Find(p => p.Id == PlayerId)!.PlayerHand;
        GameState.SaveLoadGame.SaveGame(GameState.Id, GameState);
    }

    public IActionResult OnPostTake()
    {
        InitializeGameState();
        GameState.HandleTakeCardAction(GameState.GameConfigurations.Players[GameState.PlayerIndex]);
        GameState?.SaveLoadGame.SaveGame(GameState.Id, GameState);
        return RedirectToPage(new { GameId = GameId, PlayerId = PlayerId, Saver = Saver});
    }

    public IActionResult OnGetPlayCard(Guid gameId, Guid playerId, int cardIndex, string saver)
    {
        Saver = saver;
        GameId = gameId;
        PlayerId = playerId;
        InitializeGameState();
        Player currentPlayer = GameState.GameConfigurations.Players.Find(p => p.Id == playerId)!;
        if (!GameState.IsValidMove && !GameState.IsFirstRound)
        {
            GameState.SaveLoadGame.SaveGame(GameId, GameState);
            return RedirectToPage(new { GameId, PlayerId, Saver });
        }
        else{
            if (currentPlayer.PlayerHand.Count == 1 && GameState.IsValidMove || currentPlayer.PlayerHand.Count == 0)
            {
                GameState.GameIsOver = true;
            }
            GameState.CardOnTheTable = currentPlayer.PlayerHand[cardIndex];
            
            PlayRound(currentPlayer);
            currentPlayer.PlayerHand.RemoveAt(cardIndex);
            GameState.Dealer.DiscardPile.Add(GameState.CardOnTheTable);
            if (currentPlayer.PlayerHand.Count == 1 && GameState.IsValidMove || currentPlayer.PlayerHand.Count == 0)
            {
                GameState.GameIsOver = true;
            }
            currentPlayer.MustSkip = false;
            GameState.PlayerIndex = (GameState.PlayerIndex + 1) % GameState.GameConfigurations.Players.Count;
            GameState.SaveLoadGame.SaveGame(GameId, GameState);
            return RedirectToPage(new { GameId, PlayerId, Saver });
        }
    }
    
    public IActionResult OnPostSayUno()
    {
        InitializeGameState();
        GameState.GameConfigurations.Players.Find(p => p.Id == PlayerId)!.SaidUno = true;
        GameState.SaveLoadGame.SaveGame(GameId, GameState);
        return RedirectToPage(new { GameId = GameId, PlayerId = PlayerId, Saver });
    }
    
    public void PlayRound(Player player)
    {
        if (GameState.Dealer.DeckPile.Count == 0) GameState.ConvertDiscardPileIntoDeck();
        Card userSelectedCard = GameState.SelectedCard;
        Card activeCard = GameState.CardOnTheTable;
        switch (activeCard.CardValue)
        {
            case CardValue.Reverse:
                activeCard.WasPlayed = true;
                GameState.PlayerIndex = GameState.GameConfigurations.Players.IndexOf(player) - 1;
                GameState.UserInterface.ReverseMessage();
                GameState.GameConfigurations.Players.Reverse();
                break;
            case CardValue.Wild or CardValue.WildDrawFour or CardValue.WildCustomizable or CardValue.WildShuffleHands:
            {
                if (activeCard.CardValue is CardValue.WildShuffleHands)
                {
                    GameState.GameConfigurations.Players.ForEach(currentPlayer =>
                    {
                        GameState.AllPlayersCards.AddRange(currentPlayer.PlayerHand);
                        currentPlayer.PlayerHand.Clear();
                    
                    });
                    GameState.Dealer.ShuffleCards(GameState.AllPlayersCards);
                    GameState.DealCardsToPlayersAfterShuffle();
                }
                activeCard.WasPlayed = activeCard.CardValue is CardValue.Wild;
                var values = Enum.GetValues(typeof(CardColor))
                    .Cast<CardColor>()
                    .Where(c => c != CardColor.Multicolor)
                    .ToArray();
                activeCard.CardColor = (CardColor)values.GetValue(new Random().Next(values.Length))!;
                break;
            }
        }
        GameState.AddScoreToPlayerForPlayingCard(player, userSelectedCard);
        GameState.SaveLoadGame.SaveGame(GameId, GameState);
    }
    
    public void ApplyActionCardForPlayer(Player player, Card activeCard)
    {
        if(activeCard.WasPlayed) return;
        switch (activeCard.CardValue) 
        {
            case CardValue.Skip:
                GameState.PlayerIndex = (GameState.PlayerIndex + 1) % GameState.GameConfigurations.Players.Count;
                break;
            case CardValue.DrawTwo:
                GameState.DrawCardsToPlayer(player, 2);
                break;
            case CardValue.WildDrawFour:
                activeCard.WasPlayed = true;
                GameState.DrawCardsToPlayer(player, 4);
                break;
            case CardValue.WildShuffleHands:
                GameState.DealCardsToPlayersAfterShuffle();
                break;
        }
        activeCard.WasPlayed = true;
    }
}

WebApp/Pages/Play/Index.cshtml
@page
@using CardSystem
@using UnoGame
@model WebApp.Pages.Play.Index
<link rel="stylesheet" type="text/css" href="css/site.css">

<h1>Play</h1>
<h5>Reload page in <span id="reload-label">-</span></h5> 
@if (Model.GameState.GameIsOver)
{
    <h1>Game is over!</h1>
}
else
{
    <div id="game">
    <div id="game-statistics">
        <div id="game-data">
            
            <h3>@Model.GameState.GameConfigurations.Players[Model.GameState.PlayerIndex].Name's turn</h3>
            @if (Model.GameState.GameConfigurations.HaveToShowPoints)
            {
                <table>
                    <tr>
                        <th>Player</th>
                        <th>Score</th>
                    </tr>
                    @foreach (var player in Model.GameState.GameConfigurations.Players)
                    {
                        <tr>
                            <td>@player.Name</td>
                            <td>@player.Score</td>
                        </tr>
                    }
                </table>
            }
            <table>
                <tr>
                    <th>Deck</th>
                    <th>Discard Pile</th>
                </tr>
                <tr>
                    <td>@Model.GameState.Dealer.DeckPile.Count()</td>
                    <td>@Model.GameState.Dealer.DiscardPile.Count()</td>
                </tr>
            </table>
            <table>
                <tr>
                    <th>Player</th>
                    <th>Cards</th>
                </tr>
                @foreach (var player in Model.GameState.GameConfigurations.Players)
                {
                    <tr>
                        <td>@player.Name</td>
                        <td>@player.PlayerHand.Count</td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <div id="game-field">
        <div id="active-card-area">
            <div class="card card-@Model.GameState.CardOnTheTable.CardColor.ToString()!.ToLower()">
                <div class="oval">
                    <span class="text text-@Model.GameState.CardOnTheTable.CardColor.ToString()!.ToLower()">@CardSymbols.GetSymbol(@Model.GameState.CardOnTheTable.CardValue)</span>
                </div>
            </div>
        </div>
        <div id="player-cards">
            @for (int i = 0; i < Model.PlayerCardsInGame.Count; i++)
            {
                if (Model.PlayerId == Model.GameState.GameConfigurations.Players[Model.GameState.PlayerIndex].Id)
                {
                    var i1 = i;
                    if (Model.GameState.CheckIfValidMove(Model.PlayerCardsInGame[i], Model.GameState.CardOnTheTable))
                    {
                        <a asp-page="/Play/Index" asp-page-handler="PlayCard" asp-route-gameId="@Model.GameId" asp-route-playerId="@Model.PlayerId" asp-route-cardIndex="@(i1)" asp-route-saver="@Model.Saver">
                            <div class="card card-@Model.PlayerCardsInGame[i1].CardColor.ToString()!.ToLower()">
                                <div class="oval">
                                    <span class="text text-@Model.PlayerCardsInGame[i1].CardColor.ToString()!.ToLower()">@CardSymbols.GetSymbol(@Model.PlayerCardsInGame[i1].CardValue)</span>
                                </div>
                            </div>
                        </a> //if card suitable, works as link
                    }
                    else
                    {
                        <div class="card card-@Model.PlayerCardsInGame[i1].CardColor.ToString()!.ToLower()">
                            <div class="oval">
                                <span class="text text-@Model.PlayerCardsInGame[i1].CardColor.ToString()!.ToLower()">@CardSymbols.GetSymbol(@Model.PlayerCardsInGame[i1].CardValue)</span>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="card card-@Model.PlayerCardsInGame[i].CardColor.ToString()!.ToLower()">
                        <div class="oval">
                            <span class="text text-@Model.PlayerCardsInGame[i].CardColor.ToString()!.ToLower()">@CardSymbols.GetSymbol(@Model.PlayerCardsInGame[i].CardValue)</span>
                        </div>
                    </div> // if not your turn, link absent
                }
            }
        </div>
        @if (Model.PlayerId == Model.GameState.GameConfigurations.Players[Model.GameState.PlayerIndex].Id)
        {
            <div id="game-buttons">
                <form method="post" asp-page-handler="Take" asp-route-gameId="@Model.GameId" asp-route-playerId="@Model.PlayerId"  asp-route-saver="@Model.Saver">
                    <button type="submit">TAKE</button> 
                </form>
                
                @* if active player, take button appears and can be clicked *@
                
                @if (Model.GameState.GameConfigurations.Players[Model.GameState.PlayerIndex].PlayerHand.Count == 2)
                {
                    <form method="post" asp-page-handler="SayUno" asp-route-gameId="@Model.GameId" asp-route-playerId="@Model.PlayerId"  asp-route-saver="@Model.Saver">
                        <button type="submit">UNO</button>
                    </form>
                }
            </div>
        }
    </div>
    </div>
}

@section Scripts
{ 
    <script>
        let timerValue = 2
        let timerLabel = document.querySelector("#reload-label")
        setInterval(() => {
            timerValue--;
            timerLabel.innerHTML = timerValue.toString();
            if (timerValue <= 0){
                window.location.reload();
            }    
        }, 500);
    </script>
}